/* Generated by crustc (CRusty++ v0.1) from examples/m2_structs.crust */
/* Do not edit by hand. */
#include <stdint.h>

typedef struct Point {
    int32_t x;
    int32_t y;
} Point;

int main(void) {
    Point p = (Point){ .x = 3, .y = 4 };
    int32_t sum = (p.x + p.y);
    int32_t scaled = ((sum * 2) - 14);
    return scaled;
}
