/* Generated by crustc (CRusty++ v0.1) from examples/m2b_checked_if.crust */
/* Do not edit by hand. */
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

static void crx_panic(const char *msg) {
    fprintf(stderr, "panic: %s\n", msg);
    exit(101);
}

static int32_t crx_checked_add_i32(int32_t a, int32_t b) {
    int64_t r = (int64_t)a + (int64_t)b;
    if (r < INT32_MIN || r > INT32_MAX) crx_panic("i32 addition overflow");
    return (int32_t)r;
}

static int32_t crx_checked_sub_i32(int32_t a, int32_t b) {
    int64_t r = (int64_t)a - (int64_t)b;
    if (r < INT32_MIN || r > INT32_MAX) crx_panic("i32 subtraction overflow");
    return (int32_t)r;
}

int main(void) {
    int32_t a = 20;
    int32_t b = 22;
    int32_t sum = crx_checked_add_i32(a, b);
    int32_t diff = crx_checked_sub_i32(b, a);
    bool ok = (sum == 42);
    if (ok) {
        if ((diff < 5)) {
            return 0;
        } else {
            return 2;
        }
    } else {
        return 1;
    }
}
