/* Generated by crustc (CRusty++ v0.1) from examples/m2c_loops.crust */
/* Do not edit by hand. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

static void crx_panic(const char *msg) {
    fprintf(stderr, "panic: %s\n", msg);
    exit(101);
}

static int32_t crx_checked_add_i32(int32_t a, int32_t b) {
    int64_t r = (int64_t)a + (int64_t)b;
    if (r < INT32_MIN || r > INT32_MAX) crx_panic("i32 addition overflow");
    return (int32_t)r;
}

static int32_t crx_checked_mul_i32(int32_t a, int32_t b) {
    int64_t r = (int64_t)a * (int64_t)b;
    if (r < INT32_MIN || r > INT32_MAX) crx_panic("i32 multiplication overflow");
    return (int32_t)r;
}

static int32_t crx_checked_div_i32(int32_t a, int32_t b) {
    if (b == 0) crx_panic("i32 division by zero");
    if (a == INT32_MIN && b == -1) crx_panic("i32 division overflow");
    return a / b;
}

int main(void) {
    int32_t sum = 0;
    int32_t i = 1;
    while ((i <= 5)) {
        sum = crx_checked_add_i32(sum, i);
        i = crx_checked_add_i32(i, 1);
    }
    int32_t count = 0;
    int32_t n = 0;
    for (;;) {
        if ((n >= 10)) {
            break;
        }
        int32_t cur = n;
        n = crx_checked_add_i32(n, 1);
        int32_t half = crx_checked_div_i32(cur, 2);
        int32_t twice = crx_checked_mul_i32(half, 2);
        if ((twice != cur)) {
            continue;
        }
        count = crx_checked_add_i32(count, 1);
    }
    int32_t result = 1;
    if ((sum == 15)) {
        if ((count == 5)) {
            result = 0;
        } else {
            result = 2;
        }
    }
    return result;
}
