/* Generated by crustc (CRusty++ v0.1) from examples/m2d_numeric_types.crust */
/* Do not edit by hand. */
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

static void crx_panic(const char *msg) {
    fprintf(stderr, "panic: %s\n", msg);
    exit(101);
}

static int8_t crx_checked_add_i8(int8_t a, int8_t b) {
    int64_t r = (int64_t)a + (int64_t)b;
    if (r < INT8_MIN || r > INT8_MAX) crx_panic("i8 addition overflow");
    return (int8_t)r;
}

static int16_t crx_checked_sub_i16(int16_t a, int16_t b) {
    int64_t r = (int64_t)a - (int64_t)b;
    if (r < INT16_MIN || r > INT16_MAX) crx_panic("i16 subtraction overflow");
    return (int16_t)r;
}

static int32_t crx_checked_sub_i32(int32_t a, int32_t b) {
    int64_t r = (int64_t)a - (int64_t)b;
    if (r < INT32_MIN || r > INT32_MAX) crx_panic("i32 subtraction overflow");
    return (int32_t)r;
}

static int64_t crx_checked_add_i64(int64_t a, int64_t b) {
    if ((b > 0 && a > INT64_MAX - b) || (b < 0 && a < INT64_MIN - b))
        crx_panic("i64 addition overflow");
    return a + b;
}

static uint8_t crx_checked_add_u8(uint8_t a, uint8_t b) {
    uint64_t r = (uint64_t)a + (uint64_t)b;
    if (r > UINT8_MAX) crx_panic("u8 addition overflow");
    return (uint8_t)r;
}

static uint16_t crx_checked_sub_u16(uint16_t a, uint16_t b) {
    uint64_t r = (uint64_t)a - (uint64_t)b;
    if (r > UINT16_MAX) crx_panic("u16 subtraction overflow");
    return (uint16_t)r;
}

static uint32_t crx_checked_sub_u32(uint32_t a, uint32_t b) {
    uint64_t r = (uint64_t)a - (uint64_t)b;
    if (r > UINT32_MAX) crx_panic("u32 subtraction overflow");
    return (uint32_t)r;
}

static uint64_t crx_checked_add_u64(uint64_t a, uint64_t b) {
    uint64_t r = a + b;
    if (r < a) crx_panic("u64 addition overflow");
    return r;
}

static size_t crx_checked_mul_usize(size_t a, size_t b) {
    size_t r = a * b;
    if (a != 0 && r / a != b) crx_panic("usize multiplication overflow");
    return r;
}

typedef struct Header {
    uint8_t magic;
    uint16_t version;
    uint32_t length;
    uint64_t checksum;
} Header;

int main(void) {
    int8_t s8 = crx_checked_add_i8((-100), 27);
    int16_t s16 = crx_checked_sub_i16(1000, 1);
    int32_t s32 = crx_checked_sub_i32(2000000000, 1);
    int64_t s64 = crx_checked_add_i64(9000000000, 1);
    uint8_t u_8 = crx_checked_add_u8(200, 55);
    uint16_t u_16 = crx_checked_sub_u16(60000, 1);
    uint32_t u_32 = crx_checked_sub_u32(4000000000, 1);
    uint64_t u_64 = crx_checked_add_u64(18000000000000000000u, 1);
    size_t sz = crx_checked_mul_usize(4096, 2);
    Header h = (Header){ .magic = 255, .version = 2, .length = 1024, .checksum = 100000 };
    int32_t result = 0;
    if ((s8 < 0)) {
    } else {
        result = 1;
    }
    if ((s16 == 999)) {
    } else {
        result = 1;
    }
    if ((s32 > 0)) {
    } else {
        result = 1;
    }
    if ((s64 > 9000000000)) {
    } else {
        result = 1;
    }
    if ((u_8 == 255)) {
    } else {
        result = 1;
    }
    if ((u_16 < 60000)) {
    } else {
        result = 1;
    }
    if ((u_32 > 0)) {
    } else {
        result = 1;
    }
    if ((u_64 > 0)) {
    } else {
        result = 1;
    }
    if ((sz == 8192)) {
    } else {
        result = 1;
    }
    if ((h.checksum == 100000)) {
    } else {
        result = 1;
    }
    return result;
}
