/* Generated by crustc (CRusty++ v0.1) from examples/m2e_casts.crust */
/* Do not edit by hand. */
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

static void crx_panic(const char *msg) {
    fprintf(stderr, "panic: %s\n", msg);
    exit(101);
}

static int32_t crx_checked_add_i32(int32_t a, int32_t b) {
    int64_t r = (int64_t)a + (int64_t)b;
    if (r < INT32_MIN || r > INT32_MAX) crx_panic("i32 addition overflow");
    return (int32_t)r;
}

static int8_t crx_cast_to_i8(uint8_t bits) {
    if (bits <= (uint8_t)INT8_MAX) return (int8_t)bits;
    return (int8_t)(bits - (uint8_t)INT8_MIN) + INT8_MIN;
}

static int16_t crx_cast_to_i16(uint16_t bits) {
    if (bits <= (uint16_t)INT16_MAX) return (int16_t)bits;
    return (int16_t)(bits - (uint16_t)INT16_MIN) + INT16_MIN;
}

static int32_t crx_cast_to_i32(uint32_t bits) {
    if (bits <= (uint32_t)INT32_MAX) return (int32_t)bits;
    return (int32_t)(bits - (uint32_t)INT32_MIN) + INT32_MIN;
}

int main(void) {
    int8_t a8 = (-5);
    int32_t a32 = (int32_t)(a8);
    uint8_t b8 = 200;
    uint32_t b32 = (uint32_t)(b8);
    uint8_t c = (uint8_t)((-1));
    int8_t d = crx_cast_to_i8((uint8_t)(255));
    uint8_t e = (uint8_t)(300);
    int16_t f = crx_cast_to_i16((uint16_t)(65535));
    size_t g = (size_t)(1000);
    int32_t sum = crx_checked_add_i32(a32, crx_cast_to_i32((uint32_t)(b32)));
    int32_t result = 0;
    if ((c == 255)) {
    } else {
        result = 1;
    }
    if ((d < 0)) {
    } else {
        result = 1;
    }
    if ((e == 44)) {
    } else {
        result = 1;
    }
    if ((f == (-1))) {
    } else {
        result = 1;
    }
    if ((g == 1000)) {
    } else {
        result = 1;
    }
    if ((sum == 195)) {
    } else {
        result = 1;
    }
    return result;
}
