/* Generated by crustc (CRusty++ v0.1) from examples/m3a_slices.crust */
/* Do not edit by hand. */
#include <stddef.h>
#include <stdint.h>

static int32_t crx_cast_to_i32(uint32_t bits) {
    if (bits <= (uint32_t)INT32_MAX) return (int32_t)bits;
    return (int32_t)(bits - (uint32_t)INT32_MIN) + INT32_MIN;
}

typedef struct { const char *ptr; size_t len; } crx_str;

typedef struct { const uint8_t *ptr; size_t len; } crx_slice_u8;

typedef struct Greeting {
    crx_str text;
    size_t size;
} Greeting;

typedef struct Blob {
    crx_slice_u8 data;
    size_t size;
} Blob;

int main(void) {
    crx_str msg = (crx_str){ "Hello, CRusty++!", 16 };
    size_t n = msg.len;
    int32_t n32 = crx_cast_to_i32((uint32_t)(msg.len));
    Greeting g = (Greeting){ .text = (crx_str){ "abc", 3 }, .size = 3 };
    size_t glen = g.text.len;
    int32_t result = 0;
    if ((n == 16)) {
    } else {
        result = 1;
    }
    if ((n32 == 16)) {
    } else {
        result = 1;
    }
    if ((glen == 3)) {
    } else {
        result = 1;
    }
    if ((g.size == 3)) {
    } else {
        result = 1;
    }
    return result;
}
